# Generated by Django 5.0.3 on 2024-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_group', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
    ]
