# Generated by Django 5.0.3 on 2024-03-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributeddata',
            name='data',
        ),
    ]
