# Generated by Django 5.0.3 on 2024-03-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_remove_distributeddata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100)),
                ('channel_subscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DistributedData',
        ),
    ]
